let config = {
    "ANIMATE": true,
    "DIMENSIONS": 2,
    "FISH_CX": 400,
    "FISH_CY": 400,
    "FISH_WIDTH": 15,
    "FISH_HEIGHT": 5,
    "FISH_DEFINITION": 4,
    "FISH_STARTING_ANGLE": 0,
    "FISH_TURN_SPEED": 2 * Math.PI,
    "FISH_ACCELERATION": 0.4, // Pixels/s^2
    "FPS": 30,
    "ROTATION_ANGLE": 0.06,
    "COHESION_FORCE": 6.0,
    "COHESION_LEADER_WEIGHT": 1.0,
    "SEPARATION_FORCE": 7.5,
    "ANGLE_ALIGNMENT_FORCE": 0.05,
    "SPEED_ALIGNMENT_FORCE": 0.01,
    "ANGLE_LEADER_ALIGNMENT_FORCE": 2.0,
    "FISH_DEFAULT_SPEED": 1,
    "BOID_MIN_SPEED": 0.5,
    "FISH_MIN_SPEED": 1,
    "FISH_MAX_SPEED": 2.5,
    "BREAKING_SPEED": 1,
    "SEPARATION_DISTANCE": 10,
    "OBSTACLE_DIVERSION_FACTOR": 2.5,
};

export default config;
